/**
 * Site-wide configuration — the single source of truth for SEO.
 *
 * Consumed by the metadata generator, `robots.ts`, `sitemap.ts`, and the
 * JSON-LD structured-data helper. Update the placeholder values per project.
 */
import { publicEnv } from "@/env";

export const siteConfig = {
  name: "Kimi Antonelli — GRIDO1 Racing Systems",
  description:
    "Driver_012. Kimi Antonelli, rookie season 2026 with the Mercedes-AMG F1 Team. Next race: Belgian GP, Spa-Francorchamps.",
  /**
   * Public origin, no trailing slash. Drives canonical URLs, OG tags, the
   * sitemap, and JSON-LD. Set `NEXT_PUBLIC_SITE_URL` in production.
   */
  url: publicEnv.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  /**
   * Default Open Graph / Twitter share image (path under `public/`).
   * Generated by `scripts/generate-open-graph.mjs` — regenerate it rather
   * than editing the PNG, so it stays in step with the hero.
   */
  ogImage: "/open-graph.png",
  twitterHandle: "@grido1",
  author: "GRIDO1 Racing Systems",
  /**
   * Browser theme-color (address bar / PWA). Matches `--background`; a
   * mismatch here is the thin coloured band above the page on mobile Safari.
   */
  themeColor: "#f7fafb",
} as const;
